/* =========================================================
   C++ CODE LAB — js/language.js
   All UI translations + the language-switcher + i18n apply logic.
   5 fully working languages: English, বাংলা, हिंदी, Español, Français.
========================================================= */

const LANGUAGES = [
  { code: 'en', label: 'English', native: 'EN' },
  { code: 'bn', label: 'বাংলা',   native: 'BN' },
  { code: 'hi', label: 'हिंदी',    native: 'HI' },
  { code: 'es', label: 'Español', native: 'ES' },
  { code: 'fr', label: 'Français', native: 'FR' }
];

const TRANSLATIONS = {
  "en": {
    "nav_home": "Home",
    "nav_learn": "Learn C++",
    "nav_programs": "Programs",
    "nav_practice": "Practice",
    "nav_plan": "30-Day Plan",
    "nav_resources": "Resources",
    "nav_about": "About",
    "hero_title_1": "Master C++.",
    "hero_title_2": "Build Powerful Programs.",
    "hero_subtitle": "Learn C++ from fundamentals to problem solving.",
    "btn_start": "Start Learning",
    "btn_explore": "Explore Projects",
    "why_title": "Why Learn C++?",
    "why_sub": "C++ is powerful, versatile and remains one of the most in-demand programming languages in the world. Here's why you should learn it:",
    "roadmap_title": "C++ Learning Roadmap",
    "roadmap_sub": "Follow this step-by-step path to become a C++ pro.",
    "projects_title": "30+ C++ Projects",
    "projects_sub": "Build real-world projects and strengthen your concepts with hands-on coding.",
    "search_placeholder": "Search C++ projects...",
    "filter_all": "All",
    "filter_beginner": "Beginner",
    "filter_intermediate": "Intermediate",
    "filter_advanced": "Advanced",
    "show_all": "Show All Projects",
    "show_less": "Show Less",
    "view_code": "View Code",
    "view_details": "View Details",
    "copy_code": "Copy Code",
    "copied": "Copied!",
    "practice_title": "C++ Practice Zone",
    "practice_sub": "Sharpen your skills with hands-on problems. Try to solve before revealing the answer.",
    "reveal_solution": "Reveal Solution",
    "hide_solution": "Hide Solution",
    "plan_title": "30-Day C++ Study Plan",
    "plan_sub": "A daily roadmap from your first program to a complete project.",
    "days_completed": "Days Completed",
    "modules_completed": "Modules Completed",
    "progress": "Progress",
    "reset_progress": "Reset Progress",
    "mark_complete": "Mark Complete",
    "completed": "Completed",
    "streak_title": "Your Learning Streak",
    "current_streak": "Current Streak",
    "magic_title": "C++ Magic Trick",
    "reveal_trick": "Reveal Trick",
    "fact_title": "Did You Know?",
    "show_fact": "Show Another Fact",
    "interview_title": "C++ Interview Questions",
    "interview_sub": "Master the most commonly asked C++ interview questions.",
    "about_title": "About C++ Code Lab",
    "about_text": "I am Priyajit Paul, the creator of C++ Code Lab, a learning platform designed to make C++ programming easier to learn through practical examples, projects and problem solving.",
    "resources_title": "Resources",
    "footer_tagline": "Keep coding, keep building!",
    "footer_learn": "Learn",
    "footer_projects": "Projects",
    "footer_connect": "Connect",
    "footer_quick": "Quick Links",
    "difficulty": "Difficulty",
    "concepts": "Concepts Used",
    "expected_output": "Expected Output",
    "close": "Close",
    "hint": "Hint",
    "statement": "Problem Statement",
    "input_label": "Expected Input",
    "tagline": "Learn • Practice • Build • Master C++",
    "nav_whatis": "What is C++?",
    "whatis_badge": "Get to know the language",
    "whatis_title": "What is C++?",
    "whatis_lead": "C++ is a general-purpose, compiled programming language that blends low-level control over memory and hardware with high-level tools like classes, templates and the Standard Template Library.",
    "whatis_p1": "Created by Bjarne Stroustrup in 1979 as an extension of C, it added object-oriented and generic programming while keeping C's raw performance.",
    "whatis_p2": "Today it powers browsers, operating systems, game engines, databases and trading systems — anywhere speed and control both matter.",
    "stat_created": "Created",
    "stat_paradigms": "Paradigms Supported",
    "stat_standard": "Latest ISO Standard",
    "stat_powers": "Powers Software Like",
    "whatis_cta": "See Why It's Worth Learning",
    "why_badge": "Career-Ready Skills",
    "practice_badge": "Hands-on Zone",
    "practice_filter_label": "Filter by difficulty",
    "practice_solve_first": "Try it yourself first, then reveal the solution.",
    "lang_new_badge": "New"
  },
  "bn": {
    "nav_home": "হোম",
    "nav_learn": "সি++ শিখুন",
    "nav_programs": "প্রোগ্রাম",
    "nav_practice": "অনুশীলন",
    "nav_plan": "৩০-দিনের পরিকল্পনা",
    "nav_resources": "রিসোর্স",
    "nav_about": "সম্পর্কে",
    "hero_title_1": "সি++ আয়ত্ত করুন।",
    "hero_title_2": "শক্তিশালী প্রোগ্রাম তৈরি করুন।",
    "hero_subtitle": "মৌলিক বিষয় থেকে সমস্যা সমাধান পর্যন্ত সি++ শিখুন।",
    "btn_start": "শেখা শুরু করুন",
    "btn_explore": "প্রজেক্ট দেখুন",
    "why_title": "কেন সি++ শিখবেন?",
    "why_sub": "সি++ শক্তিশালী, বহুমুখী এবং বিশ্বের সবচেয়ে চাহিদাসম্পন্ন প্রোগ্রামিং ভাষাগুলোর একটি।",
    "roadmap_title": "সি++ শেখার রোডম্যাপ",
    "roadmap_sub": "একজন সি++ বিশেষজ্ঞ হতে ধাপে ধাপে এই পথ অনুসরণ করুন।",
    "projects_title": "৩০+ সি++ প্রজেক্ট",
    "projects_sub": "হাতে-কলমে কোডিং করে বাস্তব প্রজেক্ট তৈরি করুন এবং ধারণা মজবুত করুন।",
    "search_placeholder": "সি++ প্রজেক্ট খুঁজুন...",
    "filter_all": "সব",
    "filter_beginner": "শিক্ষানবিস",
    "filter_intermediate": "মধ্যম",
    "filter_advanced": "উন্নত",
    "show_all": "সব প্রজেক্ট দেখুন",
    "show_less": "কম দেখুন",
    "view_code": "কোড দেখুন",
    "view_details": "বিস্তারিত দেখুন",
    "copy_code": "কোড কপি করুন",
    "copied": "কপি হয়েছে!",
    "practice_title": "সি++ অনুশীলন জোন",
    "practice_sub": "হাতে-কলমে সমস্যা সমাধান করে দক্ষতা বাড়ান।",
    "reveal_solution": "সমাধান দেখুন",
    "hide_solution": "সমাধান লুকান",
    "plan_title": "৩০-দিনের সি++ পরিকল্পনা",
    "plan_sub": "প্রথম প্রোগ্রাম থেকে সম্পূর্ণ প্রজেক্ট পর্যন্ত দৈনিক রোডম্যাপ।",
    "days_completed": "সম্পন্ন দিন",
    "modules_completed": "সম্পন্ন মডিউল",
    "progress": "অগ্রগতি",
    "reset_progress": "অগ্রগতি রিসেট করুন",
    "mark_complete": "সম্পন্ন চিহ্নিত করুন",
    "completed": "সম্পন্ন হয়েছে",
    "streak_title": "আপনার শেখার ধারাবাহিকতা",
    "current_streak": "বর্তমান ধারাবাহিকতা",
    "magic_title": "সি++ ম্যাজিক ট্রিক",
    "reveal_trick": "ট্রিক দেখুন",
    "fact_title": "আপনি কি জানেন?",
    "show_fact": "আরেকটি তথ্য দেখুন",
    "interview_title": "সি++ ইন্টারভিউ প্রশ্ন",
    "interview_sub": "সবচেয়ে বেশি জিজ্ঞাসিত সি++ ইন্টারভিউ প্রশ্নগুলো আয়ত্ত করুন।",
    "about_title": "সি++ কোড ল্যাব সম্পর্কে",
    "about_text": "আমি প্রিয়জিৎ পাল, সি++ কোড ল্যাবের নির্মাতা, যা ব্যবহারিক উদাহরণ, প্রজেক্ট এবং সমস্যা সমাধানের মাধ্যমে সি++ প্রোগ্রামিং শেখাকে সহজ করার জন্য তৈরি একটি শেখার প্ল্যাটফর্ম।",
    "resources_title": "রিসোর্স",
    "footer_tagline": "কোডিং চালিয়ে যান, তৈরি করতে থাকুন!",
    "footer_learn": "শিখুন",
    "footer_projects": "প্রজেক্ট",
    "footer_connect": "যোগাযোগ",
    "footer_quick": "দ্রুত লিংক",
    "difficulty": "কঠিনতা",
    "concepts": "ব্যবহৃত ধারণা",
    "expected_output": "প্রত্যাশিত আউটপুট",
    "close": "বন্ধ করুন",
    "hint": "ইঙ্গিত",
    "statement": "সমস্যা বিবরণ",
    "input_label": "প্রত্যাশিত ইনপুট",
    "tagline": "শিখুন • অনুশীলন • তৈরি করুন • C++ আয়ত্ত করুন",
    "nav_whatis": "C++ কী?",
    "whatis_badge": "ভাষাটি সম্পর্কে জানুন",
    "whatis_title": "C++ কী?",
    "whatis_lead": "C++ একটি জেনারেল-পারপাস, কম্পাইলড প্রোগ্রামিং ভাষা যা মেমরি ও হার্ডওয়্যারের উপর লো-লেভেল নিয়ন্ত্রণকে ক্লাস, টেমপ্লেট এবং STL-এর মতো হাই-লেভেল টুলের সাথে একত্রিত করে।",
    "whatis_p1": "১৯৭৯ সালে Bjarne Stroustrup C-এর সম্প্রসারণ হিসেবে এটি তৈরি করেন, যা C-এর গতি বজায় রেখে অবজেক্ট-ওরিয়েন্টেড ও জেনেরিক প্রোগ্রামিং যুক্ত করে।",
    "whatis_p2": "আজ এটি ব্রাউজার, অপারেটিং সিস্টেম, গেম ইঞ্জিন, ডেটাবেস এবং ট্রেডিং সিস্টেম চালায় — যেখানেই গতি ও নিয়ন্ত্রণ দুটোই গুরুত্বপূর্ণ।",
    "stat_created": "তৈরি হয়েছে",
    "stat_paradigms": "সমর্থিত প্যারাডাইম",
    "stat_standard": "সর্বশেষ ISO স্ট্যান্ডার্ড",
    "stat_powers": "যেসব সফটওয়্যার চালায়",
    "whatis_cta": "কেন শেখা উচিত দেখুন",
    "why_badge": "ক্যারিয়ার-রেডি দক্ষতা",
    "practice_badge": "হ্যান্ডস-অন জোন",
    "practice_filter_label": "কঠিনতা অনুসারে ফিল্টার করুন",
    "practice_solve_first": "প্রথমে নিজে চেষ্টা করুন, তারপর সমাধান দেখুন।",
    "lang_new_badge": "নতুন"
  },
  "hi": {
    "nav_home": "होम",
    "nav_learn": "C++ सीखें",
    "nav_programs": "प्रोग्राम",
    "nav_practice": "अभ्यास",
    "nav_plan": "30-दिन योजना",
    "nav_resources": "संसाधन",
    "nav_about": "परिचय",
    "hero_title_1": "C++ में महारत हासिल करें।",
    "hero_title_2": "शक्तिशाली प्रोग्राम बनाएं।",
    "hero_subtitle": "मूल बातों से लेकर समस्या समाधान तक C++ सीखें।",
    "btn_start": "सीखना शुरू करें",
    "btn_explore": "प्रोजेक्ट देखें",
    "why_title": "C++ क्यों सीखें?",
    "why_sub": "C++ शक्तिशाली, बहुमुखी है और दुनिया की सबसे मांग वाली प्रोग्रामिंग भाषाओं में से एक है।",
    "roadmap_title": "C++ सीखने का रोडमैप",
    "roadmap_sub": "C++ विशेषज्ञ बनने के लिए इस चरण-दर-चरण मार्ग का पालन करें।",
    "projects_title": "30+ C++ प्रोजेक्ट्स",
    "projects_sub": "हाथों-हाथ कोडिंग के साथ वास्तविक प्रोजेक्ट बनाएं और अपनी अवधारणाओं को मजबूत करें।",
    "search_placeholder": "C++ प्रोजेक्ट खोजें...",
    "filter_all": "सभी",
    "filter_beginner": "शुरुआती",
    "filter_intermediate": "मध्यम",
    "filter_advanced": "उन्नत",
    "show_all": "सभी प्रोजेक्ट देखें",
    "show_less": "कम दिखाएं",
    "view_code": "कोड देखें",
    "view_details": "विवरण देखें",
    "copy_code": "कोड कॉपी करें",
    "copied": "कॉपी हो गया!",
    "practice_title": "C++ अभ्यास क्षेत्र",
    "practice_sub": "व्यावहारिक समस्याओं के साथ अपने कौशल को निखारें।",
    "reveal_solution": "समाधान दिखाएं",
    "hide_solution": "समाधान छुपाएं",
    "plan_title": "30-दिन C++ अध्ययन योजना",
    "plan_sub": "पहले प्रोग्राम से एक पूर्ण प्रोजेक्ट तक दैनिक रोडमैप।",
    "days_completed": "पूर्ण दिन",
    "modules_completed": "पूर्ण मॉड्यूल",
    "progress": "प्रगति",
    "reset_progress": "प्रगति रीसेट करें",
    "mark_complete": "पूर्ण चिह्नित करें",
    "completed": "पूर्ण हुआ",
    "streak_title": "आपकी सीखने की लकीर",
    "current_streak": "वर्तमान लकीर",
    "magic_title": "C++ मैजिक ट्रिक",
    "reveal_trick": "ट्रिक दिखाएं",
    "fact_title": "क्या आप जानते हैं?",
    "show_fact": "एक और तथ्य दिखाएं",
    "interview_title": "C++ इंटरव्यू प्रश्न",
    "interview_sub": "सबसे अधिक पूछे जाने वाले C++ इंटरव्यू प्रश्नों में महारत हासिल करें।",
    "about_title": "C++ कोड लैब के बारे में",
    "about_text": "मैं प्रियजीत पॉल हूं, C++ कोड लैब का निर्माता, जो व्यावहारिक उदाहरणों, प्रोजेक्ट्स और समस्या समाधान के माध्यम से C++ प्रोग्रामिंग सीखना आसान बनाने के लिए बनाया गया एक शिक्षण मंच है।",
    "resources_title": "संसाधन",
    "footer_tagline": "कोडिंग जारी रखें, निर्माण जारी रखें!",
    "footer_learn": "सीखें",
    "footer_projects": "प्रोजेक्ट्स",
    "footer_connect": "जुड़ें",
    "footer_quick": "त्वरित लिंक",
    "difficulty": "कठिनाई",
    "concepts": "उपयोग की गई अवधारणाएं",
    "expected_output": "अपेक्षित आउटपुट",
    "close": "बंद करें",
    "hint": "संकेत",
    "statement": "समस्या विवरण",
    "input_label": "अपेक्षित इनपुट",
    "tagline": "सीखें • अभ्यास करें • बनाएं • C++ में महारत हासिल करें",
    "nav_whatis": "C++ क्या है?",
    "whatis_badge": "भाषा के बारे में जानें",
    "whatis_title": "C++ क्या है?",
    "whatis_lead": "C++ एक जनरल-पर्पस, कंपाइल्ड प्रोग्रामिंग भाषा है जो मेमोरी और हार्डवेयर पर लो-लेवल कंट्रोल को क्लासेस, टेम्पलेट्स और STL जैसे हाई-लेवल टूल्स के साथ जोड़ती है।",
    "whatis_p1": "1979 में Bjarne Stroustrup द्वारा C के विस्तार के रूप में बनाई गई, इसने C के प्रदर्शन को बनाए रखते हुए ऑब्जेक्ट-ओरिएंटेड और जेनेरिक प्रोग्रामिंग जोड़ी।",
    "whatis_p2": "आज यह ब्राउज़र, ऑपरेटिंग सिस्टम, गेम इंजन, डेटाबेस और ट्रेडिंग सिस्टम चलाता है — जहाँ भी गति और नियंत्रण दोनों मायने रखते हैं।",
    "stat_created": "स्थापित",
    "stat_paradigms": "समर्थित पैराडाइम",
    "stat_standard": "नवीनतम ISO मानक",
    "stat_powers": "इन सॉफ्टवेयर को चलाता है",
    "whatis_cta": "जानें यह क्यों सीखने लायक है",
    "why_badge": "करियर-रेडी स्किल्स",
    "practice_badge": "हैंड्स-ऑन ज़ोन",
    "practice_filter_label": "कठिनाई के अनुसार फ़िल्टर करें",
    "practice_solve_first": "पहले खुद हल करने की कोशिश करें, फिर समाधान देखें।",
    "lang_new_badge": "नया"
  },
  "es": {
    "nav_home": "Inicio",
    "nav_learn": "Aprender C++",
    "nav_programs": "Programas",
    "nav_practice": "Practicar",
    "nav_plan": "Plan de 30 Días",
    "nav_resources": "Recursos",
    "nav_about": "Acerca de",
    "nav_whatis": "¿Qué es C++?",
    "tagline": "Aprende • Practica • Crea • Domina C++",
    "hero_title_1": "Domina C++.",
    "hero_title_2": "Crea Programas Poderosos.",
    "hero_subtitle": "Aprende C++ desde lo básico hasta la resolución de problemas.",
    "btn_start": "Empezar a Aprender",
    "btn_explore": "Explorar Proyectos",
    "whatis_badge": "Conoce el lenguaje",
    "whatis_title": "¿Qué es C++?",
    "whatis_lead": "C++ es un lenguaje de programación compilado y de propósito general que combina control de bajo nivel sobre la memoria y el hardware con herramientas de alto nivel como clases, plantillas y la STL.",
    "whatis_p1": "Creado por Bjarne Stroustrup en 1979 como una extensión de C, añadió programación orientada a objetos y genérica sin perder el rendimiento de C.",
    "whatis_p2": "Hoy impulsa navegadores, sistemas operativos, motores de juegos, bases de datos y sistemas de trading, donde la velocidad y el control importan.",
    "stat_created": "Creado en",
    "stat_paradigms": "Paradigmas Compatibles",
    "stat_standard": "Último Estándar ISO",
    "stat_powers": "Impulsa Software Como",
    "whatis_cta": "Descubre por qué vale la pena aprenderlo",
    "why_title": "¿Por qué Aprender C++?",
    "why_badge": "Habilidades para tu Carrera",
    "why_sub": "C++ es potente, versátil y sigue siendo uno de los lenguajes más demandados del mundo. Aquí te decimos por qué deberías aprenderlo:",
    "roadmap_title": "Hoja de Ruta de C++",
    "roadmap_sub": "Sigue este camino paso a paso para dominar C++.",
    "projects_title": "30+ Proyectos de C++",
    "projects_sub": "Construye proyectos reales y refuerza tus conceptos con código práctico.",
    "search_placeholder": "Buscar proyectos de C++...",
    "filter_all": "Todos",
    "filter_beginner": "Principiante",
    "filter_intermediate": "Intermedio",
    "filter_advanced": "Avanzado",
    "show_all": "Ver Todos los Proyectos",
    "show_less": "Ver Menos",
    "view_code": "Ver Código",
    "view_details": "Ver Detalles",
    "copy_code": "Copiar Código",
    "copied": "¡Copiado!",
    "practice_title": "Zona de Práctica de C++",
    "practice_badge": "Zona Práctica",
    "practice_sub": "Mejora tus habilidades con problemas prácticos. Intenta resolverlos antes de ver la respuesta.",
    "practice_filter_label": "Filtrar por dificultad",
    "practice_solve_first": "Intenta resolverlo tú mismo antes de ver la solución.",
    "reveal_solution": "Ver Solución",
    "hide_solution": "Ocultar Solución",
    "plan_title": "Plan de Estudio de C++ de 30 Días",
    "plan_sub": "Una ruta diaria desde tu primer programa hasta un proyecto completo.",
    "days_completed": "Días Completados",
    "modules_completed": "Módulos Completados",
    "progress": "Progreso",
    "reset_progress": "Reiniciar Progreso",
    "mark_complete": "Marcar Completo",
    "completed": "Completado",
    "streak_title": "Tu Racha de Aprendizaje",
    "current_streak": "Racha Actual",
    "magic_title": "Truco Mágico de C++",
    "reveal_trick": "Revelar Truco",
    "fact_title": "¿Sabías Qué?",
    "show_fact": "Mostrar Otro Dato",
    "interview_title": "Preguntas de Entrevista de C++",
    "interview_sub": "Domina las preguntas de entrevista más comunes de C++.",
    "about_title": "Acerca de C++ Code Lab",
    "about_text": "Soy Priyajit Paul, el creador de C++ Code Lab, una plataforma de aprendizaje diseñada para facilitar el aprendizaje de C++ mediante ejemplos prácticos, proyectos y resolución de problemas.",
    "resources_title": "Recursos",
    "footer_tagline": "¡Sigue programando, sigue construyendo!",
    "footer_learn": "Aprender",
    "footer_projects": "Proyectos",
    "footer_connect": "Conectar",
    "footer_quick": "Enlaces Rápidos",
    "difficulty": "Dificultad",
    "concepts": "Conceptos Usados",
    "expected_output": "Salida Esperada",
    "close": "Cerrar",
    "hint": "Pista",
    "statement": "Enunciado del Problema",
    "input_label": "Entrada Esperada",
    "lang_new_badge": "Nuevo"
  },
  "fr": {
    "nav_home": "Accueil",
    "nav_learn": "Apprendre C++",
    "nav_programs": "Programmes",
    "nav_practice": "Pratique",
    "nav_plan": "Plan de 30 Jours",
    "nav_resources": "Ressources",
    "nav_about": "À Propos",
    "nav_whatis": "Qu'est-ce que le C++ ?",
    "tagline": "Apprendre • Pratiquer • Créer • Maîtriser le C++",
    "hero_title_1": "Maîtrisez le C++.",
    "hero_title_2": "Créez des Programmes Puissants.",
    "hero_subtitle": "Apprenez le C++, des bases à la résolution de problèmes.",
    "btn_start": "Commencer",
    "btn_explore": "Explorer les Projets",
    "whatis_badge": "Découvrez le langage",
    "whatis_title": "Qu'est-ce que le C++ ?",
    "whatis_lead": "Le C++ est un langage de programmation compilé et généraliste qui allie contrôle bas niveau de la mémoire et du matériel avec des outils haut niveau comme les classes, les templates et la STL.",
    "whatis_p1": "Créé par Bjarne Stroustrup en 1979 comme extension du C, il a ajouté la programmation orientée objet et générique tout en conservant la performance du C.",
    "whatis_p2": "Aujourd'hui, il alimente des navigateurs, systèmes d'exploitation, moteurs de jeux, bases de données et systèmes de trading — partout où vitesse et contrôle comptent.",
    "stat_created": "Créé en",
    "stat_paradigms": "Paradigmes Supportés",
    "stat_standard": "Dernière Norme ISO",
    "stat_powers": "Alimente des Logiciels Comme",
    "whatis_cta": "Découvrez pourquoi l'apprendre",
    "why_title": "Pourquoi Apprendre le C++ ?",
    "why_badge": "Compétences pour votre Carrière",
    "why_sub": "Le C++ est puissant, polyvalent et reste l'un des langages les plus demandés au monde. Voici pourquoi l'apprendre :",
    "roadmap_title": "Feuille de Route C++",
    "roadmap_sub": "Suivez ce parcours étape par étape pour devenir un pro du C++.",
    "projects_title": "30+ Projets C++",
    "projects_sub": "Construisez des projets réels et renforcez vos concepts par la pratique.",
    "search_placeholder": "Rechercher des projets C++...",
    "filter_all": "Tous",
    "filter_beginner": "Débutant",
    "filter_intermediate": "Intermédiaire",
    "filter_advanced": "Avancé",
    "show_all": "Voir Tous les Projets",
    "show_less": "Voir Moins",
    "view_code": "Voir le Code",
    "view_details": "Voir les Détails",
    "copy_code": "Copier le Code",
    "copied": "Copié !",
    "practice_title": "Zone de Pratique C++",
    "practice_badge": "Zone Pratique",
    "practice_sub": "Améliorez vos compétences avec des problèmes pratiques. Essayez avant de voir la réponse.",
    "practice_filter_label": "Filtrer par difficulté",
    "practice_solve_first": "Essayez de résoudre vous-même avant de voir la solution.",
    "reveal_solution": "Voir la Solution",
    "hide_solution": "Masquer la Solution",
    "plan_title": "Plan d'Étude C++ de 30 Jours",
    "plan_sub": "Un parcours quotidien de votre premier programme à un projet complet.",
    "days_completed": "Jours Complétés",
    "modules_completed": "Modules Complétés",
    "progress": "Progrès",
    "reset_progress": "Réinitialiser",
    "mark_complete": "Marquer Terminé",
    "completed": "Terminé",
    "streak_title": "Votre Série d'Apprentissage",
    "current_streak": "Série Actuelle",
    "magic_title": "Astuce Magique C++",
    "reveal_trick": "Révéler l'Astuce",
    "fact_title": "Le Saviez-Vous ?",
    "show_fact": "Afficher un Autre Fait",
    "interview_title": "Questions d'Entretien C++",
    "interview_sub": "Maîtrisez les questions d'entretien C++ les plus courantes.",
    "about_title": "À Propos de C++ Code Lab",
    "about_text": "Je suis Priyajit Paul, le créateur de C++ Code Lab, une plateforme d'apprentissage conçue pour faciliter l'apprentissage du C++ à travers des exemples pratiques, des projets et la résolution de problèmes.",
    "resources_title": "Ressources",
    "footer_tagline": "Continuez à coder, continuez à construire !",
    "footer_learn": "Apprendre",
    "footer_projects": "Projets",
    "footer_connect": "Contact",
    "footer_quick": "Liens Rapides",
    "difficulty": "Difficulté",
    "concepts": "Concepts Utilisés",
    "expected_output": "Sortie Attendue",
    "close": "Fermer",
    "hint": "Indice",
    "statement": "Énoncé du Problème",
    "input_label": "Entrée Attendue",
    "lang_new_badge": "Nouveau"
  }
};

const LANG_STORAGE_KEY = 'cpplab_lang';
let currentLang = localStorage.getItem(LANG_STORAGE_KEY) || 'en';

function getDict() {
  return TRANSLATIONS[currentLang] || TRANSLATIONS.en;
}

function t(key, fallback) {
  const dict = getDict();
  return dict[key] || TRANSLATIONS.en[key] || fallback || key;
}

/* Renders the dropdown list + wires up the switcher button. */
function initLangSwitcher() {
  const btn = document.getElementById('langBtn');
  const menu = document.getElementById('langMenu');
  const label = document.getElementById('langLabel');
  if (!btn || !menu || !label) return;

  menu.innerHTML = LANGUAGES.map(l => `
    <li role="menuitem" data-lang="${l.code}" class="${l.code === currentLang ? 'active' : ''}">
      <span class="lang-native">${l.native}</span>
      <span class="lang-full">${l.label}</span>
      ${(l.code === 'es' || l.code === 'fr') ? `<span class="lang-badge">${t('lang_new_badge','New')}</span>` : ''}
    </li>
  `).join('');

  label.textContent = currentLang.toUpperCase();

  btn.addEventListener('click', (e) => {
    e.stopPropagation();
    const isOpen = menu.classList.toggle('open');
    btn.setAttribute('aria-expanded', String(isOpen));
  });
  document.addEventListener('click', () => {
    menu.classList.remove('open');
    btn.setAttribute('aria-expanded', 'false');
  });

  menu.querySelectorAll('li').forEach(item => {
    item.addEventListener('click', () => {
      currentLang = item.getAttribute('data-lang');
      localStorage.setItem(LANG_STORAGE_KEY, currentLang);
      label.textContent = currentLang.toUpperCase();
      menu.querySelectorAll('li').forEach(li => li.classList.remove('active'));
      item.classList.add('active');
      menu.classList.remove('open');
      applyTranslations();
      document.dispatchEvent(new CustomEvent('languagechange', { detail: { lang: currentLang } }));
    });
  });
}

/* Applies the current language dictionary to every [data-i18n] / [data-i18n-ph] element. */
function applyTranslations() {
  const dict = getDict();
  document.documentElement.setAttribute('lang', currentLang);
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key]) el.textContent = dict[key];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    if (dict[key]) el.setAttribute('placeholder', dict[key]);
  });
}
